language: python
python: "3.6"
cache: pip
script: pipenv run test
install:
  - pip install pipenv
  - pipenv install --deploy
env:
  global:
    - secure: nOwBY35rD0nNpPeoIiMeDv1gEYoqtq1ivvGMZPFBeBVgDOMRtQIDk8jS/gFLpfmFBIRZr7LetUC1Cp9Mk5gD3N6GJqdvg6fBhigh5SciBAKynAO7uryhxHoAfsFp58RAmc8cmqetadMdL3YTkrM5FIThWpjXtaO1O3TNH0C+s+7AeTBdGfzCPEUTN7dRHZ/HVGz1SFqu6clNlxag7z80egV9MAVhOQIFzJyub8kp8iAxinxhlYmqtd8YjEELR6a9KgA8DFillMZLdWuvSps7gcNY6I9pE9w2SFeIIReU0b+/fbJuwYR5MykpvwDSETGhr+b2YTfhWk8MGkGNcgUytsd0hqeD82l1GcZejCV3KXCfnXCN59f7xtXA6WSBCD5Wz6+vOdvr6B0dXZjI9nMk+bKsTXHc3gbIv4+FPTduJJSm2TNvPrnBa1STiP8E8z6CDbt9Vam+2BYImhzxnpWG4tT2xm5+dAPzZYfmgPQoUyCBzxvXilIRDreR0h5mUd6wdn3tbjT6udNJCjS2SsZBp12GaONdKUzDOeqdqtL+FI/+jnd95DknYSVll/LDgm1joCc1kF3YpVj7YQUevheHlCNK9A+7OtYEu93Hvy5JtNXpWbIb+zIJlyttLYImucYHVPE+Mn2s+fZMUonr4BUdefFzdTA0xuBq9D8LuzU4hZM=
    - secure: GJQ9qpH+29iKc6GdK2PIej2ytKIXcl6uM1Rgh1NbNw53MmUkP7buue1Dye+xfWJL6EuMdeaRjTroQS/aK3XTjSh0BmbyXz5gHSwSAcTNQ6d4URXb56xnHD4gV0o7sJpGYOloqILR1qIxv4VEh3gXuokK3ohrkmOVvr3bqhoI2pGmjnvrk0h5Zas844vZL4IXfEq7eapFBB3N8vA4WT/iQfuBrKPxBJMuiW92nGev2wsk6esLcRPXA+D1zoqOq31JG8reG6qu3vbmYjwR+lC7GXve995OBKSG6DkX10F8PW4bWUTZUog/9pJBenGgl4jnDZ0K4NrXoLZz6EFKtKyGOxHPjX+PjjlLK7pxcF/+g6nV4e9+J/0QuaHzd5YiUyFcQwYbD3PjoFGzTaxSSfyiwoBt6HnTc8hY6mAIq4gPWswYOdDtKffC8JxdchieYJubALW2E/kd+7ufBb+cNa4tWUIJs/e2sxnKjVgHiAXh9SZRfaO+sqtdtNKoSN7RPbciUi/YW2faBVLH1rmILRzEHNYRXiiRzwm529QKMT9V/iDPzhDsuYQho9FeWDbU8XR745a2lJmAQADWWo21BDq7LTEAdZ6rJHMk8iBDNuLbNFS2hL+syL2h13ZaFbVfj/WyRp/P4cF1hDe6GzVL6hUAcUJCTTtSo72Q5PvMUHef/LE=
    - secure: GovrnJdJpxo2dWWiqIk/cW/VRdF1C+twGLXKUgPmrHp4GX93e495hhjASHa72HJU286acW3FGTyUgwTujKm04/W4NCtOGYz6QbYxo/0jpkXAcA0t2kPxV6x0gccbz0q6NIQWnM6NtPD4I8ZBIKpnsccgQQXHyyXqiHfI4IlzZZ3W9kXuUr1AoZawKj5P2vGo8TdsH24ptRcY//0a9LBT0OAkJUXiUq/5pImBIkKJrEah8V0a1N7ItFl3ZNo5FWvet9Hjv5T32gHOxCYtYV+540Fvvpi0QauBTFZVLqVlxnt9lbkCmobDAKfnoNavyimngDls1j8U9jtq6fUpBPS4DQVEKi4Zn5JMQKvo6q8segW9IgfIvVQiKAhcsbaqdYcby1DgaHzuNlv00d6yEhsIe8AAAjuUacTXBG7PXb9Dc93nF1wQvzXeMtHEM4ab0DM0kiIpU0Gj5oRSsu3HUf0e1MXqjWaxZK/JERwGzXsL6It5T6hoh0WsRCTi5NizPSHBS36gRTEJ9W8zBWfJVSVscv4tALtFZf+3gl+GoLNM7jViYvomvbmqiV/SfuQDTHe/yRD0UnEoc0A50i+Hk2wt11yLpJLEV5RM2UfmISY7eN+an0w0qS5xzeF/7gQqk0C25hyQmZfg2By/yl5l7Fww6XgANpEeS/Gyds+V0mL9+Lw=
deploy:
  - provider: script
    script: python build.py cfm-reslib
    on:
      repo: CloudSnorkel/cfm-reslib
      branch: master
  - provider: script
    script: python build.py cfm-reslib -t $TRAVIS_TAG
    on:
      repo: CloudSnorkel/cfm-reslib
      tags: true
